spring:
  application:
    name: gateway-visitor
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
              allowOrigins: "*" # 跨域处理 允许所有的域
              allowMethods: # 支持  的方法
                -GET
                -POST
                -PUT
                -DELETE
      routes:
            # 唯一标识符
            - id: eshop_goods_route
              # 用户请求需要路由到该服务
              uri: http://localhost:18081
              # 路由断言
              predicates:
              # 用户请求的域名规则配置，所有以cloud.eshop.com的请求都将被路由到18081
              - Host=cloud.eshop.com**
              # 所有以/brand开始的请求，都路由到18081
              # - Path=/brand/**
              # 所有以/api/brand的请求，都被路由到18081


server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true